# Generated by Django 5.2.12 on 2026-03-15 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration", models.CharField(max_length=20, unique=True)),
                ("aircraft_type", models.CharField(blank=True, max_length=100)),
                (
                    "max_takeoff_weight",
                    models.FloatField(blank=True, help_text="MTOW in kg", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircraft",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aircraft",
                "verbose_name_plural": "Aircraft",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoadCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "maneuver_type",
                    models.CharField(
                        choices=[
                            ("pull_up", "Pull-Up"),
                            ("push_over", "Push-Over"),
                            ("roll", "Roll"),
                            ("gust", "Gust Load"),
                            ("ground", "Ground Load"),
                            ("landing", "Landing Impact"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "flight_phase",
                    models.CharField(
                        choices=[
                            ("cruise", "Cruise"),
                            ("climb", "Climb"),
                            ("descent", "Descent"),
                            ("takeoff", "Takeoff"),
                            ("landing", "Landing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "load_factor_nz",
                    models.FloatField(
                        help_text="Vertical load factor (g)",
                        validators=[
                            django.core.validators.MinValueValidator(-4.0),
                            django.core.validators.MaxValueValidator(9.0),
                        ],
                    ),
                ),
                ("speed_ktas", models.FloatField(help_text="Speed in knots TAS")),
                ("altitude_ft", models.FloatField(help_text="Altitude in feet")),
                ("is_critical", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_cases",
                        to="loads.aircraft",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Load Case",
                "verbose_name_plural": "Load Cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_bending_moment", models.FloatField(help_text="Nm")),
                ("max_shear_force", models.FloatField(help_text="N")),
                ("safety_factor", models.FloatField(default=1.5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("flagged", "Flagged — Needs Review"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "load_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="loads.loadcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
